### ISSUE TITLE
Failure to fetch NetBSD packages

### ISSUE THREAD

**Issue by outpaddling** [TritonDataCenter/pkgbuild#24]
Trying to run the setup script on NetBSD 10.0 beta with sh -x gives me the following.  Am I missing something obvious?

```
+ '[' -f /etc/shrc ']'
+ . /etc/shrc
+ BOOTSTRAP_TAR=bootstrap-netbsd-trunk-x86_64-20220718.tar.gz
+ BOOTSTRAP_SHA=f21c7f7f4ba547bf922c16ea656a9481c8bcb526
+ ftp 'https://pkgsrc.smartos.org/packages/NetBSD/bootstrap/bootstrap-netbsd-trunk-x86_64-20220718.tar.gz'
18446744073709551615:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/external/bsd/openssl/dist/ssl/statem/statem_clnt.c:1919:
ftp: Can't connect to `pkgsrc.smartos.org:https'
```

**Comment by jperkin** [comment]
Have you installed mozilla-rootcerts? For inexplicable reasons NetBSD does not ship with a working certificate store by default, so https does not work out of the box.

**Comment by outpaddling** [comment]
No, it's a pristine installation with nothing installed.
Might want to mention that requirement at:
[https://pkgsrc.smartos.org/install-on-netbsd/](https://pkgsrc.smartos.org/install-on-netbsd/).
P.S. I was in on a discussion about installing certs in pkgsrc boostrap a few years back.  The elders stated that users should decide for themselves which certs to trust.  My view is that many new users don't know what a cert is, so I made auto-pkgsrc-setup (and now desktop-installer) install them.

**Comment by outpaddling** [comment]
BTW, did you mean mozilla-rootcerts-openssl?

**Comment by jperkin** [comment]
Either.
